name: app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.1



  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.6.0
  build_runner:


flutter:

  uses-material-design: true
